import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[];page.on('pageerror',err=>errors.push(err.message));
await page.goto('http://127.0.0.1:4173');
await page.getByRole('heading',{name:'品牌官网改版'}).waitFor();
await page.getByRole('button',{name:'＋ 新建任务'}).click();
await page.getByLabel('任务名称',{exact:true}).fill('离线测试任务');
await page.getByLabel('负责人',{exact:true}).fill('测试员');
await page.getByLabel('所属阶段').fill('验收阶段');
await page.locator('#progress-range').fill('65');
await page.getByRole('button',{name:'保存',exact:true}).click();
await page.locator('.tabs').getByRole('button',{name:'任务清单'}).click();
await page.getByLabel('搜索任务').fill('离线测试');
await page.getByRole('button',{name:'离线测试任务',exact:true}).waitFor();
await page.reload();
await page.locator('.tabs').getByRole('button',{name:'任务清单'}).click();
assert.equal(await page.getByRole('button',{name:'离线测试任务',exact:true}).count(),1);
await page.locator('.tabs').getByRole('button',{name:'甘特图'}).click();
await page.locator('.gantt-bar').filter({hasText:'离线测试任务'}).click();
await page.locator('#progress-range').fill('100');
await page.getByRole('button',{name:'保存',exact:true}).click();
assert.match(await page.locator('.gantt-bar').filter({hasText:'离线测试任务'}).innerText(),/100%/);
await page.locator('.tabs').getByRole('button',{name:'思维导图'}).click();
await page.locator('.mind-leaf').filter({hasText:'离线测试任务'}).waitFor();
await page.locator('.tabs').getByRole('button',{name:'项目概览'}).click();
await page.screenshot({path:'/tmp/compass-desktop.png',fullPage:true});
await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
await page.reload();
await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
await page.waitForTimeout(500);
await context.setOffline(true);
await page.reload();
await page.getByRole('heading',{name:'品牌官网改版'}).waitFor();
await page.locator('.tabs').getByRole('button',{name:'任务清单'}).click();
await page.getByRole('button',{name:'离线测试任务',exact:true}).click();
await page.getByLabel('备注').fill('断网后仍然可以修改任务');
await page.getByRole('button',{name:'保存',exact:true}).click();
await page.reload();
await page.locator('.tabs').getByRole('button',{name:'任务清单'}).click();
await page.getByRole('button',{name:'离线测试任务',exact:true}).click();
assert.equal(await page.getByLabel('备注').inputValue(),'断网后仍然可以修改任务');
await page.getByRole('button',{name:'取消',exact:true}).click();
await context.setOffline(false);
await page.setViewportSize({width:390,height:844});
await page.locator('.tabs').getByRole('button',{name:'项目概览'}).click();
await page.screenshot({path:'/tmp/compass-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'移动端页面不应横向溢出');
assert.deepEqual(errors,[]);
console.log('通过：任务创建、进度同步、甘特图、结构图、本地持久化、断网刷新与编辑、移动端布局。');
await browser.close();
