import './style.css';
import {uid,today,day,dateOffset,validateTask,validateData,status,summary,demo} from './model.js';
const KEY='project-compass-v1';
let data, storageError='';
try { const saved=localStorage.getItem(KEY); data=saved ? validateData(JSON.parse(saved)) : demo(); } catch { data={version:1,projects:[]}; storageError='本地数据无法读取。请导入备份恢复；原始数据未自动覆盖。'; }
let selected=data.projects[0]?.id, view='overview', query='', filter='all';
const app=document.querySelector('#app');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const project=()=>data.projects.find(p=>p.id===selected);
function persist() { try {localStorage.setItem(KEY,JSON.stringify(data));storageError='';} catch {storageError='保存失败：浏览器存储空间不足或不可用。请立即导出备份。';} }
const icons={overview:'◫',tasks:'☷',gantt:'▥',mind:'⌘'};
const labels={overview:'项目概览',tasks:'任务清单',gantt:'甘特图',mind:'思维导图'};
function pill(t){const s=status(t);return `<span class="badge ${s==='已完成'?'done':s==='已延期'?'late':s==='进行中'?'active':'pending'}">${s}</span>`;}
function visibleTasks(){return (project()?.tasks||[]).filter(t=>(`${t.name} ${t.owner} ${t.phase}`.toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||status(t)===filter));}
function render(){
 const p=project(), stats=summary(p?.tasks||[]);
 app.innerHTML=`<aside class="sidebar"><a class="brand" href="#"><span class="brand-icon">◈</span> 项目罗盘<span class="brand-en">COMPASS</span></a><div class="workspace"><span class="workspace-icon">工</span><div>我的工作空间<small>个人工作台</small></div></div><div class="nav-label">工作空间</div><nav>${Object.entries(labels).map(([key,label])=>`<button class="nav-item ${view===key?'selected':''}" data-view="${key}"><span>${icons[key]}</span>${label}${key==='tasks'?`<small>${stats.total}</small>`:''}</button>`).join('')}</nav><div class="project-heading">我的项目<button id="new-project" aria-label="新建项目">＋</button></div><div class="project-list">${data.projects.map(p=>`<button data-project="${p.id}" class="project-item ${selected===p.id?'current':''}"><span class="project-dot"></span>${escape(p.name)}</button>`).join('')}</div><div class="sidebar-bottom"><div class="local-note"><span>◉</span> 数据保存在此浏览器<small>定期导出备份，安心管理工作</small></div><div class="profile"><span class="avatar">我</span><div>项目负责人<small>个人工作空间</small></div></div></div></aside><div class="shell"><header class="topbar"><div>工作空间 <span>/</span> ${escape(p?.name||'新项目')}</div><div class="top-actions"><button class="text-button" id="import">↥ 导入</button><button class="text-button" id="export">↧ 导出备份</button><span class="avatar small">我</span></div></header><main>${storageError?`<div class="warning" role="alert">${escape(storageError)}</div>`:''}<div class="page-heading"><div><div class="eyebrow">PROJECT WORKSPACE <span>／ ${labels[view]}</span></div><h1>${escape(p?.name||'开启你的第一个项目')} <span class="project-tag">${p?'项目进行中':'欢迎'}</span></h1><p>${escape(p?.description||'把目标拆解成工作，让计划与进度清晰可见。')}</p></div><div class="heading-actions">${p?'<button class="button subtle" id="edit-project">项目设置</button><button class="button primary" id="add-task">＋ 新建任务</button>':'<button class="button primary" id="create-first">＋ 创建项目</button>'}</div></div>${p?`<div class="tabs">${Object.entries(labels).map(([key,label])=>`<button data-view="${key}" class="${view===key?'on':''}">${icons[key]} ${label}</button>`).join('')}</div>${view==='overview'?overview(p,stats):view==='tasks'?taskView():view==='gantt'?gantt(p):mind(p)}`:'<section class="empty big"><span>◈</span><h2>好项目，从一个清晰的计划开始</h2><p>创建项目，添加工作任务，再用甘特图安排时间。</p></section>'}<footer>项目罗盘 <span>让每一份计划，稳步向前。</span></footer></main></div><input id="file-input" type="file" accept="application/json,.json" hidden><dialog id="modal"></dialog><div id="toast" role="status"></div>`;
 bind();
}
function overview(p,s){
 const phases=[...new Set(p.tasks.map(t=>t.phase||'未分组'))];
 return `<div class="stats"><article><div>整体进度 <span>◔</span></div><strong>${s.progress}<small>%</small></strong><div class="meter"><i style="width:${s.progress}%"></i></div><p>所有任务进度的平均值</p></article><article><div>任务总数 <span>▤</span></div><strong>${s.total}<small>项</small></strong><p><b>${s.total-s.completed}</b> 项工作待完成</p></article><article><div>已完成任务 <span>✓</span></div><strong>${s.completed}<small>项</small></strong><p><span class="green">${s.total?Math.round(s.completed/s.total*100):0}%</span> 的任务已完成</p></article><article><div>延期任务 <span>◷</span></div><strong>${s.overdue}<small>项</small></strong><p>${s.overdue?'需要关注，及时调整计划':'进度可控，继续保持'}</p></article></div><div class="overview-grid"><section class="card"><div class="section-title"><h2>阶段进展</h2><span>项目路线图</span></div>${phases.length?phases.map((phase,i)=>{const ts=p.tasks.filter(t=>(t.phase||'未分组')===phase),x=summary(ts);return `<div class="phase-row"><span class="phase-number">0${i+1}</span><div class="phase-info"><b>${escape(phase)}</b><small>${x.completed} / ${ts.length} 项任务已完成</small></div><div class="phase-progress"><span>${x.progress}%</span><div class="meter"><i style="width:${x.progress}%"></i></div></div></div>`;}).join(''):'<div class="empty">添加任务后查看阶段进展</div>'}</section><section class="card focus-card"><div class="section-title"><h2>接下来要做</h2><span class="live-dot">待办</span></div>${p.tasks.filter(t=>t.progress<100).sort((a,b)=>a.end.localeCompare(b.end)).slice(0,4).map(t=>`<button class="focus-task" data-edit="${t.id}"><span class="task-check"></span><div><b>${escape(t.name)}</b><small>${escape(t.owner||'未分配')} · ${escape(t.end)} 截止</small></div>${pill(t)}</button>`).join('')||'<div class="empty">暂无待办任务，做得很好！</div>'}<button class="all-tasks" data-view="tasks">查看所有任务 →</button></section></div><section class="card overview-table"><div class="section-title"><h2>项目任务 <small>${s.total}</small></h2><button class="text-button" data-view="tasks">查看全部 →</button></div>${table(p.tasks.slice(0,5))}</section>`;
}
function table(tasks){return tasks.length?`<div class="table-scroll"><table><thead><tr><th>任务名称</th><th>负责人</th><th>状态</th><th>时间计划</th><th>进度</th><th></th></tr></thead><tbody>${tasks.map(t=>`<tr><td><button class="task-name" data-edit="${t.id}">${escape(t.name)}</button><small class="task-phase">${escape(t.phase||'未分组')}</small></td><td><span class="person-icon">${escape((t.owner||'?').slice(0,1))}</span>${escape(t.owner||'未分配')}</td><td>${pill(t)}</td><td class="dates">${escape(t.start.slice(5))} <span>→</span> ${escape(t.end.slice(5))}</td><td><div class="table-progress"><div class="meter"><i style="width:${t.progress}%"></i></div><span>${t.progress}%</span></div></td><td><button class="edit-button" data-edit="${t.id}" aria-label="编辑 ${escape(t.name)}">⋯</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">暂无任务。点击“新建任务”，输入第一项工作。</div>';}
function taskView(){return `<section class="card"><div class="task-toolbar"><h2>全部任务 <small>${project().tasks.length}</small></h2><div class="filters"><input id="search" placeholder="搜索任务、负责人或阶段" aria-label="搜索任务" value="${escape(query)}"><select id="status-filter" aria-label="筛选任务状态">${[['all','全部状态'],...['未开始','进行中','已完成','已延期'].map(s=>[s,s])].map(([v,l])=>`<option value="${v}" ${filter===v?'selected':''}>${l}</option>`).join('')}</select></div></div><div id="task-results">${table(visibleTasks())}</div></section>`;}
function gantt(p){
 if(!p.tasks.length)return '<section class="card empty">添加带日期的任务后，即可查看甘特图。</section>';
 const start=p.tasks.reduce((a,t)=>t.start<a?t.start:a,p.tasks[0].start),end=p.tasks.reduce((a,t)=>t.end>a?t.end:a,p.tasks[0].end),count=day(end)-day(start)+1;
 const width=count>180?5:count>60?16:34;
 const interval=count>180?30:count>60?7:1;
 return `<section class="card gantt-card"><div class="section-title"><h2>项目时间线</h2><span>${start} — ${end} <span class="legend-dot"></span> 已完成进度</span></div><p class="chart-help">点击任务条编辑日期和进度 · 横向滚动查看完整计划</p><div class="gantt-scroll"><div class="gantt-grid" style="--timeline:${count*width}px;--day:${width}px"><div class="gantt-label gantt-head">任务 / 负责人</div><div class="gantt-days">${Array.from({length:Math.ceil(count/interval)},(_,i)=>`<span style="width:${Math.min(interval,count-i*interval)*width}px">${dateOffset(start,i*interval).slice(5)}</span>`).join('')}</div>${p.tasks.map(t=>`<div class="gantt-label"><b>${escape(t.name)}</b><small>${escape(t.owner||'未分配')}</small></div><div class="gantt-track">${day(today())>=day(start)&&day(today())<=day(end)?`<i class="today-line" style="left:${(day(today())-day(start))*width+width/2}px"></i>`:''}<button class="gantt-bar ${t.progress===100?'complete':''}" data-edit="${t.id}" aria-label="${escape(t.name)}，进度 ${t.progress}%" style="left:${(day(t.start)-day(start))*width}px;width:${(day(t.end)-day(t.start)+1)*width}px"><i style="width:${t.progress}%"></i><span>${escape(t.name)} · ${t.progress}%</span></button></div>`).join('')}</div></div></section>`;
}
function mind(p){const phases=[...new Set(p.tasks.map(t=>t.phase||'未分组'))];return `<section class="card mind-card"><div class="section-title"><h2>工作结构图</h2><span>项目 → 阶段 → 任务</span></div><p class="chart-help">任务自动按阶段组织，点击节点即可编辑。添加或修改阶段，结构图会同步更新。</p><div class="mind-scroll"><div class="mind-map"><div class="mind-root">◈ ${escape(p.name)}</div><div class="mind-branches">${phases.map(phase=>`<div class="mind-branch"><div class="mind-phase">${escape(phase)}</div><div class="mind-leaves">${p.tasks.filter(t=>(t.phase||'未分组')===phase).map(t=>`<button data-edit="${t.id}" class="mind-leaf"><span>${escape(t.name)}</span><small>${t.progress}%</small></button>`).join('')}</div></div>`).join('')||'<div class="empty">新建任务，搭建你的工作结构。</div>'}</div></div></div></section>`;}
function bind(){
 app.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>{view=el.dataset.view;render();});
 app.querySelectorAll('[data-project]').forEach(el=>el.onclick=()=>{selected=el.dataset.project;query='';filter='all';render();});
 bindEdit();
 for(const id of ['new-project','create-first']) app.querySelector(`#${id}`)?.addEventListener('click',()=>projectModal());
 app.querySelector('#edit-project')?.addEventListener('click',()=>projectModal(project()));
 app.querySelector('#add-task')?.addEventListener('click',()=>taskModal());
 app.querySelector('#search')?.addEventListener('input',e=>{query=e.target.value;app.querySelector('#task-results').innerHTML=table(visibleTasks());bindEdit();});
 app.querySelector('#status-filter')?.addEventListener('change',e=>{filter=e.target.value;app.querySelector('#task-results').innerHTML=table(visibleTasks());bindEdit();});
 app.querySelector('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`项目罗盘备份-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 app.querySelector('#import').onclick=()=>app.querySelector('#file-input').click();
 app.querySelector('#file-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const incoming=validateData(JSON.parse(await file.text()));if(!confirm('导入将替换当前所有项目。建议先导出备份。确定继续吗？'))return;data=incoming;selected=data.projects[0]?.id;persist();render();toast('备份已导入');}catch(err){toast(`导入失败：${err.message}`);}};
}
function bindEdit(){app.querySelectorAll('[data-edit]').forEach(el=>el.onclick=()=>taskModal(project().tasks.find(t=>t.id===el.dataset.edit)));}
function toast(message){const el=app.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4000);}
function openModal(title,body,onSave,onDelete){const modal=app.querySelector('#modal');modal.innerHTML=`<form><div class="modal-heading"><h2>${title}</h2><button type="button" id="close-modal" aria-label="关闭">×</button></div>${body}<p id="form-error" role="alert"></p><div class="modal-footer">${onDelete?'<button type="button" class="button danger" id="delete-item">删除</button>':''}<span></span><button type="button" class="button subtle" id="cancel-modal">取消</button><button class="button primary" type="submit">保存</button></div></form>`;modal.showModal();modal.querySelector('#close-modal').onclick=modal.querySelector('#cancel-modal').onclick=()=>modal.close();modal.querySelector('form').onsubmit=e=>{e.preventDefault();try{onSave(Object.fromEntries(new FormData(e.target)));persist();modal.close();render();toast('已保存');}catch(err){modal.querySelector('#form-error').textContent=err.message;}};modal.querySelector('#delete-item')?.addEventListener('click',()=>{if(confirm('确定删除？此操作无法撤销。')){onDelete();persist();modal.close();render();toast('已删除');}});}
function projectModal(p){openModal(p?'项目设置':'创建新项目',`<label>项目名称<input name="name" required maxlength="80" placeholder="例如：新产品发布计划" value="${escape(p?.name||'')}"></label><label>项目简介<textarea name="description" maxlength="300" placeholder="描述项目目标…">${escape(p?.description||'')}</textarea></label>`,values=>{if(!values.name.trim())throw new Error('请输入项目名称');if(p)Object.assign(p,{...values,name:values.name.trim()});else{const item={id:uid(),...values,name:values.name.trim(),tasks:[]};data.projects.push(item);selected=item.id;view='overview';}},p?()=>{data.projects=data.projects.filter(x=>x.id!==p.id);selected=data.projects[0]?.id;}:null);}
function taskModal(t){const phases=[...new Set(project().tasks.map(t=>t.phase))];openModal(t?'编辑任务':'新建任务',`<label>任务名称<input name="name" required maxlength="120" placeholder="这项工作需要完成什么？" value="${escape(t?.name||'')}"></label><div class="form-grid"><label>负责人<input name="owner" maxlength="40" placeholder="填写姓名" value="${escape(t?.owner||'')}"></label><label>所属阶段<input name="phase" maxlength="60" list="phase-options" placeholder="例如：项目启动" value="${escape(t?.phase||'')}"><datalist id="phase-options">${phases.map(s=>`<option value="${escape(s)}">`).join('')}</datalist></label><label>开始日期<input type="date" name="start" required value="${t?.start||today()}"></label><label>结束日期<input type="date" name="end" required value="${t?.end||dateOffset(today(),7)}"></label></div><label>完成进度 <output id="progress-value">${t?.progress||0}%</output><input name="progress" type="range" min="0" max="100" value="${t?.progress||0}" id="progress-range"></label><label>备注<textarea name="notes" maxlength="2000" placeholder="记录交付物、注意事项或进展…">${escape(t?.notes||'')}</textarea></label>`,values=>{const task=validateTask({...values,id:t?.id||uid()});if(t)Object.assign(t,task);else project().tasks.push(task);},t?()=>{project().tasks=project().tasks.filter(x=>x.id!==t.id);}:null);app.querySelector('#progress-range').oninput=e=>app.querySelector('#progress-value').textContent=`${e.target.value}%`;}
render();
if(import.meta.env.PROD && 'serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(()=>{}));}
